name: Train Model on Push to Main

on:
  push:
    branches:
      - main

jobs:
  run_model_training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Model Training on Kaggle
        uses: KevKibe/kaggle-script-action@v1.0.5
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: "Run Model Training"
          custom_script: |
            python3 -m simple_reservoir.run_small
          enable_gpu: true